### ISSUE TITLE
DÚVIDA: Parser

### ISSUE THREAD

**Issue by AmandaMuniz** [fga-gpp-mds/2017.2-DepuTinder#54]
Como que é feita a comunicação dos dados que se encontram nos dados abertos com a model presente na api?

**Comment by tulioc** [comment]
@AmandaMuniz Os detalhes de implementação ainda não sei te responder, mas basicamente seria o seguinte processo:

* Fazer um request  dos dados abertos 
* Armazenar esses dados em um csv
* Alimentar a Model com os dados do csv criado. 

Isso nos torna independente da api dos dados abertos estar rodando. Precisaríamos fazer o request apenas uma vez e teriamos os dados em um arquivo csv para utilizar de forma independente. A ideia seria apenas atualizar os dados de vez em quando. 

Tente resolver passo-a-passo sem se preocupar com a finalidade como um todo. Primeiro resolva o problema do request, uma vez que você tenha os dados, se preocupe com a construção do csv, e só depois com popular o banco com os dados do csv.

**Comment by tulioc** [comment]
@AmandaMuniz 

Um exemplo de implementação do request e armazenamento em um arquivo csv já está disponível no nosso blog. Dá uma olhada lá: [Blog do Time](https://github.com/fga-gpp-mds/2017.2-DepuTinder/wiki/Blog-do-Time) :1st_place_medal:
