### ISSUE TITLE
Duvida: Diagrama de Classe

### ISSUE THREAD

**Issue by byronkamal** [fga-gpp-mds/2017.2-DepuTinder#55]
No diagrama de classe, a classe PolitcalParty tem o atributo partyDescription. Qual a função  desse atributo? 
Outra dúvida: É necessário criar a model para todos os dados de partido politico e para todos os dados de candidato? Sendo que só será usado nome de candidato e sigla do partido para exibido no ranking.

**Comment by CalebeRios** [comment]
Acredito que o partyDescription seria o nome completo do partido, e o partyName é a sigla. Ta errado no diagrama de classe.
De acordo com o parse do Tulio, o candidato ja vem com o partido, e como tinhamos definido que não vai ter como ver a descrição do partido, acredito que não seja necessária a criação dessa classe.
Porém, a classe de politico, é muito importante ela ter todas essas informações (e algumas a mais), pois você poderá olhar os dados do candidato. Não serve só para mostrar no ranking.
