### ISSUE TITLE
DÚVIDA: Unique key prop

### ISSUE THREAD

**Issue by CalebeRios** [fga-gpp-mds/2017.2-DepuTinder#56]
Eae galera, to com um problema no map. Ele pede que a tag tenha um key, e que ela seja unica, procurei algumas formas e não consegui chegar a nenhum lugar. Acredito que o problema seja porque tenha dois maps, e um esta dentro do outro. O código esta na branch US#9AcessRanking para quem quiser mais detalhes

O erro completo é esse: ```Each child in an array or iterator should have a unique "key" prop.```

```
<AccordionItem title={`Match ${matchRanking}%`} slug={ranking.groupID} key={ranking.groupID} className="react-sanfona-item-expanded">
```

**Comment by tulioc** [comment]
Então @CalebeRios, geralmente esses erros acontecem quando você não está colocando a key no elemento certo, pra poder te ajudar precisaria de um exemplo maior do código. Tem como colocar um exemplo maior do código?

**Comment by CalebeRios** [comment]
```
<Accordion className="accordion">{
    rankingData.map((ranking) => {
        const matchRanking = ranking.groupID;
        return (
            <AccordionItem
                title={`Match ${matchRanking}%`}
                slug={ranking.groupID}
                key={ranking.groupID}
                className="react-sanfona-item-expanded"
            >
                {ranking.candidates.map((candidate) => {
                    return (
                        <div>
                            <h1>{ candidate }</h1>
                        </div>
                    );
                })}
            </AccordionItem>
        );
    })
}
</Accordion>

```

**Comment by tulioc** [comment]
@CalebeRios Você precisa adicionar a key na div que está renderizando o candidato também, não só para o AccordionItem, tenta aí.

**Comment by CalebeRios** [comment]
Bem, consegui resolver o problema. Para isso eu coloquei uma key da div que estava renderizando o candidato, como o Túlio falou acima, mas não foi o único problema. Procurando na internet achei uma solução, mas não eficaz, que era colocar como key o ```ranking.id```. Para resolver tive que passar como key o próprio ```ranking```, nesse caso, passando uma string.

**Comment by tulioc** [comment]
@CalebeRios coloca um print de como ficou o código pra quem ler poder ter uma ideia melhor da apresentação :+1:

**Comment by CalebeRios** [comment]
Aqui esta o código do que eu implementei para resolver este problema:

```JavaScript
       rankingData.map((ranking) => {
          const matchRanking = ranking.groupID;
          return (
            <AccordionItem
              title={`Match ${matchRanking}%`}
              key={matchRanking}
              className="react-sanfona-item-body accordion"
              expandedClassName="accordionBody"
              titleClassName="accordionTitle"
            >
              {ranking.candidates.map((candidate) => {
                return (
                  <div
                    key={candidate}
                    id="test"
                  >
                    <i className="material-icons small">person</i>
                    { candidate }
                  </div>
                );
              })}
            </AccordionItem>
          );
        })
```
