### ISSUE TITLE
DÚVIDA: URL na API

### ISSUE THREAD

**Issue by CalebeRios** [fga-gpp-mds/2017.2-DepuTinder#61]
Galera, to tentando subir o servidor da API que esta na devel, e ele esta quebrado.. To tentando resolver ele, mas não estou entendo a seguinte linha ```url(r'^api/', include('candidateRanking.urls'))```, ele fala que o ```include``` não esta definindo. Alguém pode me explicar o que esta sendo feito?

**Comment by gustavo2795** [comment]
Calebe, não entendi também essa linha... pq o padão é vc referenciar o nome da model...
Tenta substituí-la por url(r'^candidateRanking/', candidateRanking)

**Comment by CalebeRios** [comment]
Deu certo a princípio, mas achei alguns outros erros. Tentarei arrumar isso mais tarde.
