### ISSUE TITLE
Dúvida - Erro no teste da API - Expected a Response, but received a <class 'NoneType'>

### ISSUE THREAD

**Issue by tulioc** [fga-gpp-mds/2017.2-DepuTinder#70]
@gustavo2795 @CalebeRios 
Segui o exemplo do teste feito em 'propositions', e repliquei o código para o contexto dos 'parlamentarians'. Exemplo do código:

```Python
from django.test import TestCase
from .views import parlamentarians
from rest_framework.test import APIRequestFactory

class ParlamentariansViewTest(TestCase):
    def testRequestResponse(self):
        STATUS_CODE_APPROVED = int(200)
        factory = APIRequestFactory()
        request = factory.get('/parlamentarians')
        response = parlamentarians(request)
        self.assertEqual(response.status_code, STATUS_CODE_APPROVED)

```

Ao executar os testes, recebo o seguinte erro: ``AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>``.

A minha rota está assim:

```Python
import requests, json
from django.shortcuts import render
from .models import Parlamentarians
from rest_framework.decorators import api_view
from django.core import serializers
from django.http import HttpResponse
@api_view(['GET'])
def parlamentarians(request, format=json):
    parlamentarians = Parlamentarians.objects.all()
    if parlamentarians:
        data = serializers.serialize('json', parlamentarians)
        response = HttpResponse(data, content_type='application/json')
        return response

```

Alguém já passou por algum problema semelhante e sabe como resolver?

**Comment by CalebeRios** [comment]
Talvez seja porque você não esteja retornando um ```status``` na sua view. Experimente retornar 

```python
return Response(data, status=status.HTTP_200_OK)
```

**Comment by tulioc** [comment]
Eu dei um print no que está retornando na rota e recebi isso aqui

```<HttpResponse status_code=200, "application/json">```

Então ele está retornando status_code =( 

Vou tentar trocar o HTTPResponse para o Response, pra ver se muda alguma coisa.

**Comment by tulioc** [comment]
Consegui resolver, mas tive que alterar diversos aspectos. 

A primeira alteração foi na serializer: (Nossa serializer era uma serializer comum, e é errado utilizar uma serializer comum para models. Precisei adicionar o `serializer.ModelSerializer)`

```python
from rest_framework import serializers
from .models import Parlamentarians

class ParlamentariansSerializer(serializers.ModelSerializer): // serializers.ModelSerializer
    class Meta:
        model = Parlamentarians
        fields = ('parlamentaryPhotoPath', 'parlamentaryName', 'parlamentaryUF', 'parlamentaryPoliticalParty')

```
A segunda alteração foi na rota, que estava utilizando uma serializer comum. Agora ela utiliza a nossa própria serializer e por fim retorna uma response em JSON.

```python
from .models import Parlamentarians
from rest_framework.decorators import api_view
from .serializers import ParlamentariansSerializer
from django.http import JsonResponse
import json
@api_view(['GET'])
def parlamentarians(request):
        parlamentarians = Parlamentarians.objects.all()
        serializer = ParlamentariansSerializer(parlamentarians, many=True)
        return JsonResponse(serializer.data, safe=False)
```

E o teste escrito dessa maneira, agora está passando: 

```python
from django.test import TestCase
from .views import parlamentarians
from rest_framework.test import APIRequestFactory

class ParlamentariansViewTest(TestCase):
    def testRequestResponse(self):
        STATUS_CODE_APPROVED = int(200)
        factory = APIRequestFactory()
        request = factory.get('/parlamentarians')
        response = parlamentarians(request)
        self.assertEqual(response.status_code, STATUS_CODE_APPROVED)

```


Conclusão: Por algum motivo, a serializer estava impactando na resposta dos requests da rota. Alterando o tipo de serializer, tudo voltou a funcionar normalmente, com os testes passando!
