### ISSUE TITLE
signUpForm - Botao de Sumbit criando rota desconhecida 

### ISSUE THREAD

**Issue by gustavosinacio** [fga-gpp-mds/2017.2-DepuTinder#85]
Galera, nos deparamos com um problema ontem que até agora não conseguimos resolver. O código está em components/signUpForm.js

Esse component (que na verdade será um container) gera o layout com campos que devem ser preenchidos pelo usuário na hora do Sign Up. São quatro campos e um botão. Eis o problema: Esse botao está se comportando de uma maneira que nós não definimos, direcionando à uma rota com os valores preenchidos nos campos quando ele é apertado.

Exemplo da rota: 
http://localhost:8080/signUpForm?userName=name&userEmail=email%40email&userPassword=12345&userConfirmedPassword=12345

O que tentamos pra resolver: 
Criar outro botão - Mesmo criando um botao novo, sem deletar o anterior, ele se comporta da mesma forma.
Deletar as funções que manejam o form
Criar um onClick - O botão simplesmente ignora a função.
Colocar logs no handleSubmit - Achamos que o botão estivesse usando essa função para funcionar, mas aparentemente não é.

**Comment by tulioc** [comment]
@gustavosinacio Mesmo esquema, adicione o código do componente na issue para uma melhor compreensão do problema.
